---
kind: pipeline
type: exec
name: flake info

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: show flake show
    commands:
      - nix flake show

  - name: show flake info
    commands:
      - nix flake info

  - name: run flake checks
    commands:
      - nix flake check

trigger:
  branch:
    - main
  event:
    - push

---
kind: pipeline
type: exec
name: Build arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: Build oracle-aarch64-runner-1
    commands:
      - nix build '.#nixosConfigurations.oracle-aarch64-runner-1.config.system.build.toplevel'
      - nix run .#s3uploader $(readlink result)
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_key
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret

  - name: Build stuart
    commands:
      - nix build '.#nixosConfigurations.stuart.config.system.build.toplevel'
      - nix run .#s3uploader $(readlink result)
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_key
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret

trigger:
  branch:
    - main
  event:
    - push

---
kind: pipeline
type: exec
name: Build amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: Build netcup-x86-runner-1
    commands:
      - nix build '.#nixosConfigurations.netcup-x86-runner-1.config.system.build.toplevel'
      - nix run .#s3uploader $(readlink result)
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_key
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret

trigger:
  branch:
    - main
  event:
    - push
