labels:
  backend: local

platform: "linux/arm64"

pipeline:
  - name: setup attic
    image: bash
    commands:
      - attic login lounge-rocks https://attic.lounge.rocks $ATTIC_KEY --set-default
    secrets: [attic_key]

  - name: build and push oracle-aarch64-runner-1
    image: bash
    commands:
      - attic push lounge-rocks:the-lounge $(nix build --print-out-paths --no-link .\#nixosConfigurations.oracle-aarch64-runner-1.config.system.build.toplevel)

  - name: build and push stuart
    image: bash
    commands:
      - attic push lounge-rocks:the-lounge $(nix build --print-out-paths --no-link .\#nixosConfigurations.stuart.config.system.build.toplevel)

  - name: build and push woodpecker-server
    image: bash
    commands:
      - attic push lounge-rocks:the-lounge $(nix build --print-out-paths --no-link .\#nixosConfigurations.woodpecker-server.config.system.build.toplevel)
